### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/e-s3-evaluacion-intermedia-lauraferrandof#1]
Well done @lauraferrandof !

Some tips to improve it:

- [x] Move `li` outside 'Pokemon' component, this way it is a simple card that we can use anywhere not only inside a `ul`
- [x] Add alternative text to pokemon image (maybe the name is a good option)
- [x] Move style files next to components and finish styles
- [x] Simplify the function used to map types, it only has a line, so you can remove brackets `{}` and return
- [x] Review metadata on index.html (lang, title...)
- [x] Clean and indent

Go for it!

**Comment by lauraferrandof** [comment]
@nasivuela thanks for your feedback!!
I think I fixed everything you told me. Let me know if there's anything else I can improve!

**Comment by nasivuela** [comment]
Good job!

![](https://media.giphy.com/media/K0usvg1aP657W/giphy.gif)
